language: cpp

compiler:
  - clang

addons:
    apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-7
        - g++-7

matrix:
    include:
        - os: linux
        - os: windows
        - os: osx
          osx_image: xcode11

script:
  - mkdir build
  - cd build
  - cmake ..
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then make;                   fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ] || [ "$TRAVIS_OS_NAME" = "osx" ]; then ./tests;                fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then cmake --build . --target ALL_BUILD --config Release;   fi
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .\\Release\\tests.exe;                                 fi
